x-postgres-env: &postgres-env
  POSTGRES_USER: someuser
  POSTGRES_PASSWORD: somepass
  POSTGRES_DB: socialnet
  REPLICATION_PASSWORD: replpass

x-postgres-primary-command: &postgres-primary-command
  - postgres
  - -c
  - wal_level=replica
  - -c
  - max_wal_senders=10
  - -c
  - max_replication_slots=10
  - -c
  - hot_standby=on
  - -c
  - listen_addresses=*
  # -c
  # - synchronous_commit=on
  # -c
  # - synchronous_standby_names=FIRST 1 (postgres-replica-1, postgres-replica-2)

services:
  postgres-primary:
    image: postgres:18
    container_name: socialnet-primary
    environment: *postgres-env
    command: *postgres-primary-command
    ports:
      - "5435:5432"
    volumes:
      - postgres_primary_data:/var/lib/postgresql
      - ./replication/primary/00-replication.sh:/docker-entrypoint-initdb.d/00-replication.sh:ro
      - ./migrations/init/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U someuser -d socialnet"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

  postgres-replica-1:
    image: postgres:18
    container_name: socialnet-replica-1
    environment:
      <<: *postgres-env
      PRIMARY_HOST: postgres-primary
    entrypoint: ["/bin/bash", "/replica-entrypoint.sh"]
    ports:
      - "5436:5432"
    volumes:
      - postgres_replica_1_data:/var/lib/postgresql
      - ./replication/replica/replica-entrypoint.sh:/replica-entrypoint.sh:ro
    depends_on:
      postgres-primary:
        condition: service_healthy

  postgres-replica-2:
    image: postgres:18
    container_name: socialnet-replica-2
    environment:
      <<: *postgres-env
      PRIMARY_HOST: postgres-primary
    entrypoint: ["/bin/bash", "/replica-entrypoint.sh"]
    ports:
      - "5437:5432"
    volumes:
      - postgres_replica_2_data:/var/lib/postgresql
      - ./replication/replica/replica-entrypoint.sh:/replica-entrypoint.sh:ro
    depends_on:
      postgres-primary:
        condition: service_healthy

volumes:
  postgres_primary_data:
  postgres_replica_1_data:
  postgres_replica_2_data:
